### ISSUE TITLE
Add a `configuration.md` file to this repo and drop the DEVELOPMENT AND MAINTENANCE file

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-mattermost#101]
### Describe what should be investigated or refactored

We should document how to setup Mattermost (specifically networking and DB) like we have GitLab and GitLab runner.  We should also remove old documentation that is no longer relevant.

### Links to any relevant code

https://github.com/defenseunicorns/uds-package-gitlab/blob/main/docs/configuration.md

### Additional context

This centralizes documentation in the `uds-software-factory` repository and provides a common place for users to go to learn how to use an app.

**Comment by Racer159** [comment]
If https://github.com/defenseunicorns/uds-package-gitlab/issues/146 is completed before this issue, then object storage should be documented as well

**Comment by ericwyles** [comment]
This was completed here: https://github.com/defenseunicorns/uds-package-mattermost/pull/155
