### ISSUE TITLE
Update mattermost repo to utilize zarf composability to keep the configuration DRY 

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-mattermost#29]
### Describe what should be investigated or refactored
A standard we have developed for uds packages is to have common zarf components defines in a `common/zarf.yaml` and then have the flavor specific components import that common component. This keeps the configuration DRY and is easier to update. 

This change also entails breaking values out into three sets, upstream-values.yaml (only includes image bits for upstream flavor), registry1-values.yaml (only includes image bits for registry1 flavor), and values (or common values) which contains the rest of the base values configuration. The flavor specific ones are imported in the root level flavor components and the common values is imported in the component in `common/zarf.yaml` 

### Links to any relevant code
As an example look at the gitlab package:
[Common](https://github.com/defenseunicorns/uds-package-gitlab/blob/4ef3dd269a65cae83a29ca51654c0c6c1f9f0030/common/zarf.yaml#L8) 
[Importing common into flavored components](https://github.com/defenseunicorns/uds-package-gitlab/blob/4ef3dd269a65cae83a29ca51654c0c6c1f9f0030/zarf.yaml#L38)

### Additional context
If you have questions ask :)

**Comment by ericwyles** [comment]
Working on this one.
