### ISSUE TITLE
Improve OpenSSF Scorecard Score

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-package-mattermost#31]
### Describe what should be investigated or refactored
Improve the OpenSSF Scorecard Score.

![Screenshot 2024-02-29 at 10 41 47 AM](https://github.com/defenseunicorns/uds-package-mattermost/assets/172697/5345aea9-22f2-4cd4-b523-44eb26b2e39b)

**Comment by zachariahmiller** [comment]
agreed... Some of these are just due to the age of the repo, but the critical finding should be remediated by moving commitlint to using the common workflow like @ericwyles did for the gitlab package yesterday

**Comment by naveensrinivasan** [comment]
> [@naveensrinivasan](https://github.com/naveensrinivasan) updating the existing workflow with this should remediate that finding https://github.com/defenseunicorns/uds-package-gitlab/blob/42e1f96de45381d514ff475715a3f7d301c24c37/.github/workflows/commitlint.yaml

Thanks
