### ISSUE TITLE
[ADR] Select a backup solution for Mattermost

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-mattermost#33]
### Is your feature request related to a problem? Please describe.
**As** Ashton **I want** to be able to backup Mattermost safely **so that** I can restore it easily in the event of a disaster.

### Describe the solution you'd like

We should identify and select solutions that are able to backup the Mattermost database and critical files, and then follows the recommendations for restoration:

https://docs.mattermost.com/deploy/backup-disaster-recovery.html

These should be written in a simple ADR to capture why the final solution was chosen and a follow on implementation issue should be created.

### Additional context

We currently don't have set SLAs but should target a baseline to have something while we continue to experiment.

**Comment by zachariahmiller** [comment]
Essentially, follow normal RDS backup/snapshot practices and also backup additional files as indicated here https://docs.mattermost.com/deploy/backup-disaster-recovery.html

**Comment by oates** [comment]
closing this and tracking here instead https://github.com/defenseunicorns/uds-infrastructure/issues/600
