### ISSUE TITLE
Mattermost: Integration with keycloak

### ISSUE THREAD

**Issue by oates** [defenseunicorns/uds-package-mattermost#37]
As an app developer, I want to be logged into Mattermost after I log into UDS.

**Comment by oates** [comment]
Currently blocked by Jeff Pepr work. No task to link to for that issue for now.

**Comment by oates** [comment]
Blocked by https://github.com/defenseunicorns/uds-core/issues/263

**Comment by ericwyles** [comment]
Blocked by:
https://github.com/defenseunicorns/uds-core/issues/305
https://github.com/defenseunicorns/uds-identity-config/issues/38
https://github.com/defenseunicorns/uds-core/issues/306

**Comment by ericwyles** [comment]
Changes are probably 90% done in the draft PR linked here, just working through those two issues I listed as blockers before we can finish it out.

**Comment by ericwyles** [comment]
Will retest this once a new UDS core is released containing the fix for https://github.com/defenseunicorns/uds-identity-config/issues/68
